src/main/java/net/therap/newsapp/domain/Tag.java
package net.therap.newsapp.domain;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;

/**
 * @author sahariar.alam
 * @since 10/1/19
 */
@Entity
@Table(name = "tag")
@NamedQueries({
        @NamedQuery(name = "Tag.findAll", query = "FROM Tag"),

        @NamedQuery(name = "Tag.findByTitle", query = "FROM Tag WHERE title = :title"),

        @NamedQuery(name = "Tag.findByIds", query = "FROM Tag  WHERE id IN :ids"),
})
public class Tag implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(nullable = false, updatable = false, length = 100)
    @NotNull(message = "{app.not.empty}")
    @Size(max = 100)
    private String title;

    @ManyToOne
    @JoinColumn(name = "created_by", referencedColumnName = "id", nullable = false)
    private User createdBy;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public boolean isNew() {
        return id == 0;
    }

    @Override
    public String toString() {
        return "Tag{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", createdBy=" + createdBy +
                '}';
    }
}

src/main/java/net/therap/newsapp/domain/User.java
package net.therap.newsapp.domain;

import net.therap.newsapp.constant.AccountStatus;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author sahariar.alam
 * @since 9/29/19
 */
@Entity
@Table(name = "user")
@NamedQueries({
        @NamedQuery(name = "User.findAll", query = "FROM User"),

        @NamedQuery(name = "User.findByEmail", query = "FROM User WHERE email = :email"),

        @NamedQuery(name = "User.findByRole", query = "FROM User WHERE role = :role"),

        @NamedQuery(name = "User.findByStatus", query = "FROM User WHERE accountStatus = :status"),

        @NamedQuery(name = "User.findByRoleAndStatus",
                query = "FROM User WHERE accountStatus = :status AND role = :role")
})
public class User extends Persistent {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "first_name", nullable = false)
    @NotNull(message = "{app.not.empty}")
    @Size(min = 1, max = 100, message = "{app.first.name.length}")
    private String firstName;

    @Column(name = "last_name", nullable = false)
    @NotNull(message = "{app.canNotBeEmpty}")
    @Size(min = 1, max = 100, message = "{app.last.name.length}")
    private String lastName;

    @Column(nullable = false)
    @Size(min = 4, max = 32, message = "{app.password.length.message}")
    private String password;

    @Column(name = "user_email", nullable = false)
    @NotNull(message = "{app.not.empty}")
    private String email;

    @Column(name = "account_status", nullable = false)
    @Enumerated(EnumType.STRING)
    private AccountStatus accountStatus;

    @Size(max = 1000)
    private String address;

    @ManyToOne
    @JoinColumn(name = "university_id", nullable = false)
    @NotNull(message = "{app.user.university}")
    private University university;

    @OneToOne
    @JoinColumn(name = "role_id", referencedColumnName = "id", nullable = false)
    private Role role;

    @ManyToOne
    @JoinColumn(name = "updated_by")
    private User updatedBy;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public AccountStatus getAccountStatus() {
        return accountStatus;
    }

    public void setAccountStatus(AccountStatus accountStatus) {
        this.accountStatus = accountStatus;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public University getUniversity() {
        return university;
    }

    public User getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(User updatedBy) {
        this.updatedBy = updatedBy;
    }

    public void setUniversity(University university) {
        this.university = university;
    }

    public boolean isActivated() {
        return getAccountStatus().equals(AccountStatus.ACTIVATED);
    }

    public boolean isAuthorizedToWritePost() {
        return isSuperAdmin() || isAuthor() || isAdmin();
    }

    public boolean isBanned() {
        return accountStatus.equals(AccountStatus.BANNED);
    }

    public boolean isPending() {
        return accountStatus.equals(AccountStatus.PENDING);
    }

    public boolean isNew() {
        return id == 0;
    }

    public boolean isAdmin() {
        return role.getTitle().equals("ADMIN");
    }

    public boolean isSuperAdmin() {
        return role.getTitle().equals("SUPER_ADMIN");
    }

    public boolean isAuthor() {
        return role.getTitle().equals("AUTHOR");
    }

    public boolean isSubscriber() {
        return role.getTitle().equals("SUBSCRIBER");
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;

        User user = (User) o;

        if (id != user.id) return false;
        if (accountStatus != user.accountStatus) return false;
        if (address != null ? !address.equals(user.address) : user.address != null) return false;
        if (email != null ? !email.equals(user.email) : user.email != null) return false;
        if (firstName != null ? !firstName.equals(user.firstName) : user.firstName != null) return false;
        if (lastName != null ? !lastName.equals(user.lastName) : user.lastName != null) return false;
        if (password != null ? !password.equals(user.password) : user.password != null) return false;
        if (role != null ? !role.equals(user.role) : user.role != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = (int) (id ^ (id >>> 32));
        result = 31 * result + (firstName != null ? firstName.hashCode() : 0);
        result = 31 * result + (lastName != null ? lastName.hashCode() : 0);
        result = 31 * result + (password != null ? password.hashCode() : 0);
        result = 31 * result + (email != null ? email.hashCode() : 0);
        result = 31 * result + (accountStatus != null ? accountStatus.hashCode() : 0);
        result = 31 * result + (address != null ? address.hashCode() : 0);
        result = 31 * result + (role != null ? role.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", password='" + password + '\'' +
                ", email='" + email + '\'' +
                ", accountStatus=" + accountStatus +
                ", address='" + address + '\'' +
                ", role=" + role +
                '}';
    }
}

src/main/java/net/therap/newsapp/web/controller/HomeController.java
package net.therap.newsapp.web.controller;

import net.therap.newsapp.constant.AccountStatus;
import net.therap.newsapp.constant.PostStatus;
import net.therap.newsapp.domain.Comment;
import net.therap.newsapp.domain.News;
import net.therap.newsapp.domain.University;
import net.therap.newsapp.exception.NotFoundException;
import net.therap.newsapp.service.NewsService;
import net.therap.newsapp.service.UniversityService;
import org.apache.commons.io.IOUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.MessageSourceAccessor;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletResponse;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Date;
import java.util.Calendar;
import java.util.List;

import static net.therap.newsapp.constant.URL.*;

/**
 * @author sahariar.alam
 * @since 9/30/19
 */

@Controller
public class HomeController {

    private static final String HOME_VIEW = "home";

    private static final String NEWS_DETAIL_VIEW = "newsDetail";

    private static final String UNIVERSITY_DETAIL_WITH_NEWS_VIEW = "universityDetailWithNews";

    @Autowired
    private NewsService newsService;

    @Autowired
    private UniversityService universityService;

    @Autowired
    private MessageSourceAccessor msa;

    @RequestMapping(ROOT)
    public String showHome() {
        return REDIRECT + HOME;
    }

    @RequestMapping(HOME)
    public String showHome(Model model) {
        setReferenceData(model);
        return HOME_VIEW;
    }

    @RequestMapping(value = HOME, method = RequestMethod.POST)
    public String showHome(@ModelAttribute News news, Model model) {
        setReferenceData(model);
        if (!news.getTitle().isEmpty()) {
            model.addAttribute("result", newsService.search(news.getTitle()));
        }
        return HOME_VIEW;
    }

    @RequestMapping(COMMON_NEWS_URL)
    public String showNews(@PathVariable long id, Model model) {
        News news = newsService.findBy(id);
        Date currentDate = new Date(Calendar.getInstance().getTimeInMillis());
        if (!(news.getStatus().equals(PostStatus.PUBLISHED)) || news.getPublishDate().after(currentDate)
                || news.getEndDate().before(currentDate)
                || news.getCreatedBy().getAccountStatus().equals(AccountStatus.BANNED)) {
            throw new NotFoundException(msa.getMessage("app.resource.not.available"));
        }
        model.addAttribute("news", news);
        model.addAttribute("comment", new Comment());
        return NEWS_DETAIL_VIEW;
    }

    @RequestMapping(COMMON_UNIVERSITY_URL)
    public String showUniversity(@PathVariable long id, Model model) {
        University university = universityService.findById(id);
        model.addAttribute("university", university);
        model.addAttribute("newsList", newsService.findPublishedNewsByUniversity(university));
        return UNIVERSITY_DETAIL_WITH_NEWS_VIEW;
    }

    @RequestMapping("/p/images/{id}")
    public void getImageAsByteArray(@PathVariable long id, HttpServletResponse response) throws IOException {
        News news = newsService.findBy(id);
        InputStream inputStream = new ByteArrayInputStream(news.getImage());
        response.setContentType(MediaType.IMAGE_JPEG_VALUE);
        IOUtils.copy(inputStream, response.getOutputStream());
    }

    private void setReferenceData(Model model) {
        List<News> topThreeNews = newsService.findTopThreeNews();
        model.addAttribute("newsList", topThreeNews);
        model.addAttribute("news", new News());
    }
}

src/main/java/net/therap/newsapp/web/controller/TagController.java
package net.therap.newsapp.web.controller;

import net.therap.newsapp.constant.ApplicationConstant;
import net.therap.newsapp.domain.Tag;
import net.therap.newsapp.domain.User;
import net.therap.newsapp.exception.UnAuthorizedActionException;
import net.therap.newsapp.service.TagService;
import net.therap.newsapp.service.UserService;
import net.therap.newsapp.web.validator.TagValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.StringTrimmerEditor;
import org.springframework.context.support.MessageSourceAccessor;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.Errors;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import static net.therap.newsapp.constant.URL.*;

/**
 * @author sahariar.alam
 * @since 10/1/19
 */
@Controller
@RequestMapping(TAGS)
public class TagController {

    private static final String TAG_LIST_VIEW = "tagList";

    private static final String TAG_FORM_VIEW = "tagForm";

    @Autowired
    private TagService tagService;

    @Autowired
    private UserService userService;

    @Autowired
    private TagValidator tagExistValidator;

    @Autowired
    private MessageSourceAccessor msa;

    @InitBinder
    protected void initBinder(WebDataBinder binder) {
        binder.registerCustomEditor(String.class, new StringTrimmerEditor(true));
        binder.addValidators(tagExistValidator);
    }

    @RequestMapping(method = RequestMethod.GET)
    public String tags(Model model) {
        model.addAttribute("tags", tagService.findAll());
        return TAG_LIST_VIEW;
    }

    @RequestMapping(value = NEWS_CREATE, method = RequestMethod.GET)
    public String tagForm(Model model) {
        model.addAttribute("tag", new Tag());
        return TAG_FORM_VIEW;
    }

    @RequestMapping(value = NEWS_CREATE, method = RequestMethod.POST)
    public String tagForm(@Valid @ModelAttribute Tag tag,
                          Errors errors,
                          HttpSession session,
                          RedirectAttributes redirectAttributes) {
        if (errors.hasErrors()) {
            return TAG_FORM_VIEW;
        }
        User user = (User) session.getAttribute(ApplicationConstant.USER);
        checkSaveTagAuthorization(userService.findByEmail(user.getEmail()));
        tagService.saveNewTag(tag, user);
        redirectAttributes.addFlashAttribute("message", msa.getMessage("app.added.tag"));
        return REDIRECT + TAGS;
    }

    private void checkSaveTagAuthorization(User user) {
        if (!(user.isAdmin() || user.isSuperAdmin()) || !user.isActivated()) {
            throw new UnAuthorizedActionException(msa.getMessage("app.unauthorized.action"));
        }
    }
}

src/main/webapp/WEB-INF/views/403.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<html>

<head>
    <title>
        <spring:message code="app.unauthorized.action"/>
    </title>
</head>

<body>
<div class="text-align-center">
    <h1><spring:message code="app.unauthorized.action"/></h1>
</div>
</body>

</html>

src/main/webapp/WEB-INF/views/changeUserInfoForm.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<html>
<head>
    <title>
        <spring:message code="app.user"/>
    </title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form:form method="post" modelAttribute="profile">
                <div class="form-group">
                    <div class="form-group">
                        <label>
                            <spring:message code="app.first.name"/>
                        </label>
                        <form:input type="text" class="form-control" path="firstName"/>
                        <div>
                            <form:errors path="firstName" class="color-red"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>
                            <spring:message code="app.last.name"/>
                        </label>
                        <form:input type="text" class="form-control" path="lastName"/>
                        <div>
                            <form:errors path="lastName" class="color-red"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>
                            <spring:message code="app.address"/>
                        </label>
                        <form:input type="text" class="form-control" path="address"/>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">
                    <spring:message code="app.submit"/>
                </button>
            </form:form>
        </div>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/views/loginForm.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<html>
<head>
    <title><spring:message code="app.login"/></title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-4 box-shadow card-back">
            <div class="page-title">
                <spring:message code="app.login"/>
            </div>
            <c:if test="${message != null}">
                <div class="alert alert-info">
                    <c:out value="${message}"></c:out>
                </div>
            </c:if>
            <form:form method="post" modelAttribute="login">
                <div class="form-group">
                    <div class="card-width">
                        <form:errors cssClass="alert alert-danger" path="email"/>
                    </div>
                    <div class="form-group">
                        <label><spring:message
                                code="app.email"/></label>
                        <form:input type="email" class="form-control" path="email"/>
                    </div>
                    <div class="form-group">
                        <label><spring:message
                                code="app.password"/></label>
                        <form:input type="password" class="form-control" path="password"/>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary"><spring:message code="app.submit"/></button>
            </form:form>
        </div>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/views/newsForm.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<html>
<head>
    <title>
        <spring:message code="app.news"/>
    </title>
</head>
<body>
<div class="container">
    <div class="col-md-12">
        <c:if test="${news.id!=0}">
            <div class="page-title">
                <spring:message code="app.update.news"/>
            </div>
        </c:if>
        <c:if test="${news.id==0}">
            <div class="page-title">
                <spring:message code="app.create.news"/>
            </div>
        </c:if>
        <div class="row">
            <div class="col-md-6">
                <div class="mar-bottom-30">
                    <div>
                        <a href="/a/news" class="btn black-bg-btn">
                            <spring:message code="app.back"/>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <c:if test="${news.id!=0}">
                    <div class="mar-bottom-30 float-right">
                        <a href="/a/news/create" class="btn black-bg-btn">
                            <spring:message code="app.create.new"/>
                        </a>
                    </div>
                </c:if>
            </div>
        </div>
        <c:if test="${message != null}">
            <div class="alert alert-info max-w-400">
                <c:out value="${message}"></c:out>
            </div>
        </c:if>
        <form:form method="post" modelAttribute="news" enctype="multipart/form-data">
            <div class="form-group">
                <div class="form-group">
                    <label>
                        <spring:message code="app.title"/>
                    </label>
                    <form:input type="text" class="form-control" path="title"/>
                    <div>
                        <form:errors path="title" class="color-red"/>
                    </div>
                </div>
                <div class="form-group">
                    <label>
                        <spring:message code="app.body"/>
                    </label>
                    <form:textarea path="body" class="form-control" rows="5"></form:textarea>
                    <div>
                        <form:errors path="body" class="color-red"/>
                    </div>
                </div>
                <c:if test="${sessionScope.user.superAdmin}">
                    <div class="form-group">
                        <label>
                            <spring:message code="app.priority"/>
                        </label>
                        <form:input type="text" class="form-control" path="priority"/>
                        <div>
                            <form:errors path="priority" class="color-red"/>
                        </div>
                    </div>
                </c:if>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>
                                <spring:message code="app.publish.date"/>
                            </label>
                            <form:input type="date" class="form-control" path="publishDate"/>
                            <div>
                                <form:errors path="publishDate" class="color-red"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>
                                <spring:message code="app.end.date"/>
                            </label>
                            <form:input type="date" class="form-control" path="endDate"/>
                            <div>
                                <form:errors path="endDate" class="color-red"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <c:if test="${news.image!=null }">
                            <img src="<c:url value="/p/images/${news.id} "/>">
                        </c:if>
                        <div class="form-group">
                            <label>
                                <spring:message code="app.select.image"/>
                            </label>
                            <form:input type="file" path="imageFile"/>
                            <div>
                                <form:errors path="imageFile" class="color-red"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label>
                        <spring:message code="app.post.status"/>
                    </label>
                    <form:select class="form-control" path="status">
                        <option selected value="">
                            <spring:message code="app.select.an.option"/>
                        </option>
                        <c:forEach var="status" items="${availableStatus}">
                            <option value="${status.name()}" <c:if test="${news.status.equals(status)}">
                                <c:out value="selected"></c:out>
                            </c:if> >
                                <c:out value="${status.displayName}"></c:out>
                            </option>
                        </c:forEach>
                    </form:select>
                </div>
                <div class="form-group">
                    <label>
                        <spring:message code="app.tag"/>
                    </label>

                    <div class="tag-container-form">
                        <c:forEach var="tag" items="${news.tags}">
                            <div>
                                <c:out value="${tag.title}"/>
                            </div>
                        </c:forEach>
                    </div>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#tagModal">
                        <spring:message code="app.selectTags"/>
                    </button>
                    <div>
                        <form:errors path="tags" class="color-red"/>
                    </div>
                </div>
                <form:input type="hidden" class="form-control" path="tags" id="tag-input"/>

                <c:if test="${news.status == null || !news.status.name().equals('PUBLISHED') }">
                    <button type="submit" class="btn btn-info">
                        <spring:message code="app.submit"/>
                    </button>
                </c:if>
            </div>
        </form:form>
        <c:if test="${news.id!=0 && news.comments.size()!=0 }">
        <div>
            <div class="comment-container">
                <div>
                    <h3>
                        <spring:message code="app.comments"/>
                    </h3>
                </div>
                <c:forEach var="comment" items="${news.comments}">
                    <div class="comment">
                        <div class="comment-body">
                            <c:out value="${comment.body}"></c:out>
                        </div>
                        <div class="comment-author">
                            <c:out value="${comment.createdBy.lastName}"></c:out>
                        </div>
                        <div class="comment-date">
                            <fmt:formatDate type="date" value="${comment.created}"/>
                        </div>

                        <form:form action="/a/news/${news.id}/comment/delete" method="post" modelAttribute="comment">
                            <form:input type="hidden" path="id" value="${comment.id}"/>
                            <button type="button" class="btn btn-danger dlt-btn" id="s-${comment.id}">
                                <spring:message code="app.delete"/>
                            </button>
                            <button type="submit" class="btn btn-danger display-none" id="d-${comment.id}">
                            </button>
                        </form:form>
                    </div>
                </c:forEach>
            </div>
        </div>
    </div>
    </c:if>
</div>
<!-- Modal -->
<div class="modal fade" id="tagModal" tabindex="-1" role="dialog" aria-labelledby="tagModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="tagModalLabel"><spring:message code="app.available.tags"/></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <c:forEach var="tag" items="${allTags}">
                    <div class="form-check">
                        <input class="form-check-input tag-checkbox"
                               displayName="<c:out value=" ${tag.title} "></c:out>" type="checkbox"
                               value="<c:out value=" ${tag.id} "></c:out>">
                        <label class="form-check-label">
                            <c:out value="${tag.title}"></c:out>
                        </label>
                    </div>
                </c:forEach>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <spring:message code="app.close"/>
                </button>
                <button type="button" class="btn btn-primary" id="select-tag">
                    <spring:message code="app.select"/>
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $(document).ready(function () {
            var tagsInput = $("#tag-input").val().split(",");

            for (var c = 0; c < $(".tag-checkbox").length; c++) {
                if (listContainsElem(tagsInput, $(".tag-checkbox").eq(c).val())) {
                    $(".tag-checkbox").eq(c).prop("checked", true);
                }
            }

            function listContainsElem(list, elem) {
                function checkValue(value) {
                    return value == elem;
                }

                return list.findIndex(checkValue) != -1;
            }

            $("#select-tag").click(function () {
                $('#tagModal').modal('hide');
                var tagList = [];
                var tagNames = [];
                for (var c = 0; c < $(".tag-checkbox:checked").length; c++) {
                    tagList.push($(".tag-checkbox:checked").eq(c).val());
                    tagNames.push($(".tag-checkbox:checked").eq(c).attr("displayName"));
                }
                $("#tag-input").val(tagList.toString());
                $(".tag-container-form").empty();
                for (var c = 0; c < tagNames.length; c++) {
                    $(".tag-container-form").append("<div>" + tagNames[c] + "</div>");
                }
            });

            $(".dlt-btn").click(function () {
                let id = "#" + $(this).attr('id').replace('s', 'd');
                if (confirm("Deleting comment...")) {
                    $(id).trigger("click");
                }
            });
        });
    });
</script>
</body>
</html>